name: Colect_tests

on: 
  push:
    branches:
    - dev

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set file
      id: filesetting
      run: |
          touch .env
          echo ENVIRONMENT=dev >> .env
          cat .env
          sudo make test
  metrics:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: collect
      id: metrics
      run: |
        pip3 install -r requirements.txt
        python3 test_coverage.py fga-eps-mds_${{github.event.repo_name}}
        git config --global user.email "${{secrets.CI_EMAIL}}"
        git config --global user.name "${{secrets.CI_USERNAME}}"
        git pull
        git add *.json
        git commit -m "Generating sonarcloud metrics ${{github.event.repo_name}}"
        git push
        echo "Compile complete."
  
