name: Colect_tests

on: 
  push:
    branches:
    - dev

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set file
      id: filesetting
      run: |
          touch .env
          echo ENVIRONMENT=dev >> .env
          echo DB_URL_TEST=postgres://pumaadmin:pumaadmin@db-test:5432/puma >> .env
          echo DB_USER=pumaadmin >> .env
          echo DB_PASS=pumaadmin >> .env
          echo DB=puma >> .env
          cat .env
          sudo make test
    - name: collect
      id: metrics
      run: |
        pip3 install xmltodict
        python3 test_coverage.py fga-eps-mds_${{ github.event.repository.name }}
        git config --global user.email "${{secrets.CI_EMAIL}}"
        git config --global user.name "${{secrets.CI_USERNAME}}"
        git pull
        git add *.json
        git commit -m "Generating sonarcloud metrics ${{github.event.repo_name}}"
        git push
        echo "Compile complete."
  
